language: node_js
dist: trusty
addons:
  apt:
    sources:
      - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    packages:
      - imagemagick
      - povray
node_js:
  - node
  - 6
  - 5
